# Ragnar
docs_folder = "docs" # folder to watch for new documents for RAG
ragnar_port = 11435
top_k = 5            # top k documents pulled
prepend_context = true  # add context to paragraphs in documents before embedding for RAG

# Database
db_file = "data/lancedb"
docs_log_file = "data/docs_seen.txt"

# LLM (Open-AI compatible API)
api = "http://localhost:11434"
chat_model = "tinyllama"
embed_model = "nomic-embed-text"
chat_completions_path = "/v1/chat/completions"
embed_path = "/v1/embeddings"
embed_ndims = 768                              # if using another embed model, change this value accordingly
