# Ragnar
ragnar_port = 11435

# Database
db_file = "data/lancedb"

# LLM (Open-AI compatible API)
api = "http://localhost:11434"
chat_completions_path = "/v1/chat/completions"
embed_path = "/v1/embeddings"
embed_model = "nomic-embed-text"